### ISSUE TITLE
Relative URL's / Slug names

### ISSUE THREAD

**Issue by Epenance** [unfulvio/wp-api-menus#18]
Hi there,

Im trying to work this into a prototype im making atm, and im doing some custom routes to navigate my content such as localhost/:page

I want to be able to generate a menu with the slugs that i can then use to look up the pages rather than getting the absolute url.

I can do that with custom url's but it would be great if it could include the slug of the page when automaticly adding new pages to the menu

**Comment by marceloemanoel** [comment]
@unfulvio  can you give any directions on how to do this?

**Comment by treforcoster** [comment]
Slugs would be a plus for me too!

**Comment by joDelicious** [comment]
+1 for relative path of items

**Comment by Fahrradflucht** [comment]
It's implemented in my PR #30

**Comment by unfulvio** [comment]
thanks @Fahrradflucht for your effort, I'd be glad to merge, but I don't have much time in my hands to do many updates to this project anymore --- the biggest concern would be backwards compatibility: how would your changes affect existing users of the plugin? gregrettably, I don't have time to test extensively

**Comment by Fahrradflucht** [comment]
I would consider this change non breaking because it just adds a field with
the name object_slug to the each menu item. Until someone patched that in
by hand, in which case she wouldn't be able to automatically update anyway
that shouldn't cause any problems.
Am 22.05.2016 12:47 nachm. schrieb "Fulvio Notarstefano" <
notifications@github.com>:

**Comment by unfulvio** [comment]
@Fahrradflucht I see you created more than one PR -- which one(s) should be merged?

I'm really unable to follow this project any longer and should give it up for adoption, as long as there's someone willing to push changes here and wordpress.org SVN.

**Comment by Fahrradflucht** [comment]
@unfulvio it's #28
