### ISSUE TITLE
Empty Items Array

### ISSUE THREAD

**Issue by laustdeleuran** [unfulvio/wp-api-menus#19]
On WP 4.4.1 with WP API v2 and this plugin, I get an empty array in the `items` prop. The count still says `5`, interestingly enough.

```javascript
{
    ID: 10,
    name: "Footer",
    slug: "footer",
    description: "",
    count: 5,
    items: [ ],
    meta: {
        links: {
            collection: "http://localhost:8888/wp-json/wp/v2/menus/",
            self: "http://localhost:8888/wp-json/wp/v2/menus/10"
        }
    }
}
```

This issue [has already been reported on Wordpress.org](https://wordpress.org/support/topic/empty-items-array), but I'm reporting it here in hopes of support. 

Help? :)

**Comment by ericsvendsen** [comment]
+1.  Thanks for reposting this here - I was about to do the same thing.  This issue didn't happen for me until I upgraded to Wordpress 4.4.1.  Same thing though - the count is right but the items array is empty.

**Comment by Dobbler** [comment]
+1 Same here, 4.4.1. Count is right, empty items array..

**Comment by Dobbler** [comment]
I've submitted a pull request for this here: https://github.com/unfulvio/wp-api-menus/pull/20/files

**Comment by unfulvio** [comment]
merged, thank you, will push update on .org soon
