### ISSUE TITLE
In wordpress v 4.4.2 menu items is empty

### ISSUE THREAD

**Issue by iegorov** [unfulvio/wp-api-menus#23]
Hi !
For request
`http://localhost/wordpress/wp-json/wp-api-menus/v2/menus/3`

Result contains empty items (
`{
  "ID": 3,
  "name": "Main menu",
  "slug": "main-menu",
  "description": "",
  "count": 1,
  "items": [],
  "meta": {
    "links": {
      "collection": "http://localhost/wordpress/wp-json/wp/v2/menus/",
      "self": "http://localhost/wordpress/wp-json/wp/v2/menus/3"
    }
  }
}`

**Comment by unfulvio** [comment]
hi, are you using 1.2.1 from wordpress.org or have you checked with the latest updates from the master branch here on github?

**Comment by iegorov** [comment]
Yes, I use 1.2.1

**Comment by unfulvio** [comment]
please try downloading the plugin from the master branch of this repository and let me know if problems are solved for you

**Comment by clmcgrath** [comment]
i was having the same issue as this an i can comfirm I am no longer experiencing the problem with v1.3 built from master

**Comment by iegorov** [comment]
Yes, in 1.3 problem is solved. Thanks.
1. Clone repo or download ZIP
2. npm install
3. grunt build
4. Install WP plugin from file (wp-api-menus-1.3.0.zip in build folder)
