### ISSUE TITLE
When will 1.3.0 appear in WP plugin registry?

### ISSUE THREAD

**Issue by web2style** [unfulvio/wp-api-menus#24]
Why don't you publish it? Want to test more?

**Comment by unfulvio** [comment]
yeah I wanted to check the recent changes introduced by two PR don't break any sites first as I don't have much time myself to do many tests sorry

looking good so far -- does the master branch works good to you?

**Comment by web2style** [comment]
I didn't check yet as I don't have ftp access to the server, can install plugins via admin panel only, so no  way to check from here.

**Comment by web2style** [comment]
I downloaded master zip from here and installed it from admin panel. It works fine, thanks.
