### ISSUE TITLE
PHP 5.2 Compatability

### ISSUE THREAD

**Issue by mckernanin** [unfulvio/wp-api-menus#26]
I tried to activate this on a site running PHP 5.2.17, and got an error due to the use of anonymous functions. I'm going to try to upgrade the PHP for the site, but you should note in the readme what the minimum tested PHP version is.

Error, for reference: 

Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in wp-content/plugins/wp-api-menus/includes/wp-api-menus-v2.php on line 185

https://github.com/unfulvio/wp-api-menus/blob/master/includes/wp-api-menus-v2.php#L185

**Comment by naylin18** [comment]
I have same problem like him.  Whenever I active the plugin, I got the following error:

Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in wp-content/plugins/wp-api-menus/includes/wp-api-menus-v2.php on line 185

**Comment by naylin18** [comment]
Hi,  If you update your php to 5.4, there is no problem.  Good luck!

**Comment by mckernanin** [comment]
@naylin18 thanks, but that's not the point.

**Comment by apertureless** [comment]
Well the PHP Version is actually defined in the composer.json

>   "php": ">=5.3.2",

**Comment by unfulvio** [comment]
@apertureless had included it for wp-packagist support https://wpackagist.org/, WordPress ignores composer.json anyway

**Comment by mckernanin** [comment]
I'm going to work on this, if this is ever to be merged into / iterated on for WP core, 5.2 support is not optional (no matter how frustrating it may be)
