### ISSUE TITLE
Push a new release

### ISSUE THREAD

**Issue by hedii** [unfulvio/wp-api-menus#33]
I want to use the items slug implemented in #28 but there has not been a new release since it was merged.
Can you make a new release and make it available as an update of the plugin?

**Comment by hedii** [comment]
woops, forget it...

**Comment by unfulvio** [comment]
done :+1: 

https://github.com/unfulvio/wp-api-menus/releases/tag/1.3.1
https://wordpress.org/plugins/wp-api-menus/

**Comment by hedii** [comment]
thanks
