### ISSUE TITLE
wp menu caching?

### ISSUE THREAD

**Issue by treehau5** [unfulvio/wp-api-menus#34]
Hello,

I wanted to first say thank you for the plugin, it has helped me immensely.

I noticed there was a certain delay between when the api response updates with any modifications to the menu. Is there some internal caching going on, or is this dictated by wp or wp-api? I am relatively new to the wordpress world and learning all these things, so apologize if this question seems ignorant.

Thank you.

**Comment by Fahrradflucht** [comment]
AFAIK there is no caching going on the lives over multiple requests in the plugin.

However there is some caching going on in wordpress (mainly [OPcache](http://php.net/manual/en/book.opcache.php)).

While the question talks about the Docker image in specific you can probably extrapolate how to turn it off from [this SO answer](http://stackoverflow.com/a/35299008/4342960).
